services:
  mysql:
    image: mysql:8.1
    container_name: mysql-semaforo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_semaforo
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: welderessutti/semaforo_sql:staging
    container_name: semaforo_sql-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PROFILE: stg
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_semaforo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234